In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
df = pd.read_csv("Datafiniti_Womens_Shoes_Jun19.csv")
df

,id,dateAdded,dateUpdated,asins,brand,categories,primaryCategories,colors,dimension,ean / upc,...,prices.dateSeen,prices.isSale,prices.merchant,prices.offer,prices.returnPolicy,prices.shipping,prices.size,prices.sourceURLs,sizes,sourceURLs
0,AWpyySsJAGTnQPR7wNt4,2019-05-01T09:27:22Z,2019-05-01T09:27:22Z,NaN,City Classified,"Clothing,Shoes,Womens Shoes,All Womens Shoes",Shoes,Black,NaN,656000000000,...,2019-04-19T07:09:29Z,NaN,NaN,Online only,NaN,NaN,8,https://www.walmart.com/ip/City-Classified-Sty...,8,https://www.walmart.com/ip/City-Classified-Sty...
1,AWpyyyb3AGTnQPR7wN-u,2019-05-01T09:27:19Z,2019-05-01T09:27:19Z,NaN,Skechers,"Clothing,Shoes,Womens Shoes,All Womens Shoes",Shoes,Taupe,NaN,192000000000,...,2019-04-24T09:14:11Z,NaN,NaN,Online only,NaN,NaN,6 M US,https://www.walmart.com/ip/Skechers-Women-S-Yo...,6 M US,https://www.walmart.com/ip/Skechers-Women-S-Yo...
2,AWpyzlajAGTnQPR7wOX8,2019-05-01T09:26:59Z,2019-05-01T09:26:59Z,NaN,Floral,"Clothing,Shoes,Womens Shoes,All Womens Shoes",Shoes,Black,NaN,709000000000,...,2019-04-25T12:35:00.000Z,NaN,NaN,Online only,NaN,NaN,5,https://www.walmart.com/ip/FLORAL-Pearl-Women-...,5,https://www.walmart.com/ip/FLORAL-Pearl-Women-...
3,AWpyxomE0U_gzG0hkA1q,2019-05-01T09:26:56Z,2019-05-01T09:26:56Z,NaN,Jambu,"Clothing,Shoes,Womens Shoes,All Womens Shoes",Shoes,Black/Multi,NaN,884000000000,...,2019-04-30T19:49:00.000Z,NaN,NaN,Online only: 20% off,NaN,NaN,9.5 BM US,https://www.walmart.com/ip/Jambu-Women-s-AMAL-...,9.5 BM US,https://www.walmart.com/ip/Jambu-Women-s-AMAL-...
4,AWpyxChWJbEilcB6RhWx,2019-05-01T09:26:56Z,2019-05-01T09:26:56Z,NaN,Trotters,"Clothing,Shoes,Womens Shoes,All Womens Shoes",Shoes,White,NaN,887000000000,...,2019-04-19T07:07:46Z,NaN,NaN,Online only: 50% off,NaN,NaN,11,https://www.walmart.com/ip/Women-s-Trotters-Bl...,11,https://www.walmart.com/ip/Women-s-Trotters-Bl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,AVpighYz1cnluZ0-N8EB,2017-01-20T18:58:23Z,2019-03-04T14:28:45Z,NaN,Brinley Co.,"Womens Casual Shoes,Womens Shoes,Women's Shoes...",Shoes,"Taupe,Olive,Rust,Pewter,Black",NaN,870000000000,...,2019-02-28T21:00:00Z,False,NaN,Online only,NaN,Free Shipping on orders over $35,6,https://www.walmart.com/ip/Womens-Pointed-Toe-...,"11,6,7,8,9,6.5,7.5,8.5,10",https://www.walmart.com/ip/Brinley-Co.-Womens-...
9996,AVpiewWrilAPnD_xEkjw,2016-11-10T23:43:14Z,2019-03-04T14:28:45Z,NaN,Brinley Co.,"Womens Shoes,Clothing,Women's Shoes,All Womens...",Shoes,"Red,Rose Gold,Black,Camel,Floral,Light Grey",NaN,870000000000,...,2019-02-28T21:00:00Z,False,NaN,Online only,NaN,Free Shipping on orders over $35,6,https://www.walmart.com/ip/Womens-Classic-Bow-...,"11,6,7,8,9,6.5,7.5,8.5,10",https://www.walmart.com/ip/Brinley-Co.-Womens-...
9997,AVpiYTuB1cnluZ0-Mt5a,2017-01-17T19:08:08Z,2019-03-04T14:28:45Z,NaN,Brinley Co.,"Womens Casual Shoes,Womens Shoes,Clothing,Wome...",Shoes,"Brown,Blue,Black,Stone,Grey",NaN,870000000000,...,2019-02-28T21:00:00Z,False,NaN,Online only,NaN,Free Shipping on orders over $35,6,https://www.walmart.com/ip/Womens-Stacked-Wood...,"11,6,7,8,9,6.5,7.5,8.5,10",https://www.walmart.com/ip/Brinley-Co-Ladies-S...
9998,AVpf4QnhilAPnD_xj5BW,2017-01-18T19:03:53Z,2019-03-04T14:28:35Z,NaN,Brinley Co.,"Womens Casual Shoes,Womens Shoes,Clothing,Wome...",Shoes,"Brown,Pink,Dot,Fuchsia,Black",NaN,870000000000,...,2019-02-28T21:00:00Z,False,NaN,Online only,NaN,Free Shipping on orders over $35,6,https://www.walmart.com/ip/Womens-Cross-Strap-...,"11,6,7,8,9,6.5,7.5,10,8.5",https://www.walmart.com/ip/Womens-Cross-Strap-...
9999,AVpe5Ssl1cnluZ0-ZP9z,2017-01-20T18:58:24Z,2019-03-04T14:28:35Z,NaN,Brinley Co.,"All Womens Flats,Womens Shoes,Women's Shoes,Cl...",Shoes,"Taupe,Plum,Blue,Black,Grey",NaN,870000000000,...,2019-02-28T21:00:00Z,False,NaN,Online only,NaN,Free Shipping on orders over $35,6,https://www.walmart.com/ip/Womens-Pointed-Toe-...,"11,6,7,8,9,6.5,7.5,8.5,10",https://www.walmart.com/ip/Brinley-Co.-Womens-...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10000 non-null  object
 1   dateAdded            10000 non-null  object
 2   dateUpdated          10000 non-null  object
 3   asins                5 non-null      object
 4   brand                10000 non-null  object
 5   categories           10000 non-null  object
 6   primaryCategories    10000 non-null  object
 7   colors               10000 non-null  object
 8   dimension            465 non-null    object
 9   ean / upc            10000 non-null  int64
 10  imageURLs            2643 non-null   object
 11  keys                 10000 non-null  object
 12  manufacturer         1362 non-null   object
 13  manufacturerNumber   1431 non-null   object
 14  name                 10000 non-null  object
 15  prices.amountMax     10000 non-null  float64
 16  prices.amountMin     10000 non-null  float64
 17  prices.availability  10000 non-null  bool
 18  prices.color         10000 non-null  object
 19  prices.condition     0 non-null      float64
 20  prices.currency      10000 non-null  object
 21  prices.dateAdded     0 non-null      float64
 22  prices.dateSeen      10000 non-null  object
 23  prices.isSale        1364 non-null   object
 24  prices.merchant      0 non-null      float64
 25  prices.offer         10000 non-null  object
 26  prices.returnPolicy  0 non-null      float64
 27  prices.shipping      49 non-null     object
 28  prices.size          10000 non-null  object
 29  prices.sourceURLs    10000 non-null  object
 30  sizes                10000 non-null  object
 31  sourceURLs           10000 non-null  object
dtypes: bool(1), float64(6), int64(1), object(24)
memory usage: 2.4+ MB

In [4]:
df.describe().round()

,ean / upc,prices.amountMax,prices.amountMin,prices.condition,prices.dateAdded,prices.merchant,prices.returnPolicy
count,1.000000e+04,10000.0,10000.0,0.0,0.0,0.0,0.0
mean,7.543442e+11,72.0,72.0,NaN,NaN,NaN,NaN
std,1.971633e+11,172.0,172.0,NaN,NaN,NaN,NaN
min,1.010000e+11,6.0,6.0,NaN,NaN,NaN,NaN
25%,7.090000e+11,35.0,35.0,NaN,NaN,NaN,NaN
50%,8.290000e+11,52.0,52.0,NaN,NaN,NaN,NaN
75%,8.860000e+11,84.0,84.0,NaN,NaN,NaN,NaN
max,9.560000e+11,5000.0,5000.0,NaN,NaN,NaN,NaN

In [23]:
df.isnull().sum()

id                         0
dateAdded                  0
dateUpdated                0
asins                   9995
brand                      0
categories                 0
primaryCategories          0
colors                     0
dimension               9535
ean / upc                  0
imageURLs               7357
keys                       0
manufacturer            8638
manufacturerNumber      8569
name                       0
prices.amountMax           0
prices.amountMin           0
prices.availability        0
prices.color               0
prices.condition       10000
prices.currency            0
prices.dateAdded       10000
prices.dateSeen            0
prices.isSale           8636
prices.merchant        10000
prices.offer               0
prices.returnPolicy    10000
prices.shipping         9951
prices.size                0
prices.sourceURLs          0
sizes                      0
sourceURLs                 0
dtype: int64

In [6]:
df.shape

(10000, 32)

In [7]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, dateAdded, dateUpdated, asins, brand, categories, primaryCategories, colors, dimension, ean / upc, imageURLs, keys, manufacturer, manufacturerNumber, name, prices.amountMax, prices.amountMin, prices.availability, prices.color, prices.condition, prices.currency, prices.dateAdded, prices.dateSeen, prices.isSale, prices.merchant, prices.offer, prices.returnPolicy, prices.shipping, prices.size, prices.sourceURLs, sizes, sourceURLs]
Index: []

[0 rows x 32 columns]

In [25]:
df['asins'].value_counts().head(10)

asins
B000OCQ19S,B000OCT69A,B000AOZK60,B00B1PI8JS,B000OCRIYU,B000AP3BEW,B000OCQ19I,B000AP0R44    2
B003DSG4EM,B003DSG4GK,B003DSG4FG                                                           1
B01B6609BG                                                                                 1
B00J2IK7Z4                                                                                 1
Name: count, dtype: int64

In [26]:
df[df['asins']== 'B000OCQ19S']

Empty DataFrame
Columns: [id, dateAdded, dateUpdated, asins, brand, categories, primaryCategories, colors, dimension, ean / upc, imageURLs, keys, manufacturer, manufacturerNumber, name, prices.amountMax, prices.amountMin, prices.availability, prices.color, prices.condition, prices.currency, prices.dateAdded, prices.dateSeen, prices.isSale, prices.merchant, prices.offer, prices.returnPolicy, prices.shipping, prices.size, prices.sourceURLs, sizes, sourceURLs]
Index: []

[0 rows x 32 columns]

In [10]:
for col in df.columns: 
    if df[col].nunique() < 20:
        print(df[col].value_counts())
        print('-'*50)

asins
B000OCQ19S,B000OCT69A,B000AOZK60,B00B1PI8JS,B000OCRIYU,B000AP3BEW,B000OCQ19I,B000AP0R44    2
B003DSG4EM,B003DSG4GK,B003DSG4FG                                                           1
B01B6609BG                                                                                 1
B00J2IK7Z4                                                                                 1
Name: count, dtype: int64
--------------------------------------------------
primaryCategories
Shoes                          9746
Apparel & Accessories,Shoes     254
Name: count, dtype: int64
--------------------------------------------------
dimension
10.00 in x 4.00 in x 4.00 in     253
11.00 in x 10.00 in x 5.00 in    137
9.00 in x 10.00 in x 4.50 in      37
11.0 in x 10.0 in x 5.0 in        15
12.00 in x 11.00 in x 5.00 in      8
13.00 in x 4.00 in x 11.00 in      7
11.00 in x 10.50 in x 4.50 in      1
12.0 in x 8.0 in x 4.0 in          1
12.0 in x 11.0 in x 4.0 in         1
6.00 in x 6.00 in x 1.00 in        1
6.0 in x 6.0 in x 1.0 in           1
12.0 in x 11.0 in x 6.0 in         1
12.0 in x 10.0 in x 5.0 in         1
10.0 in x 11.5 in x 4.0 in         1
Name: count, dtype: int64
--------------------------------------------------
prices.availability
True     6269
False    3731
Name: count, dtype: int64
--------------------------------------------------
Series([], Name: count, dtype: int64)
--------------------------------------------------
prices.currency
USD    10000
Name: count, dtype: int64
--------------------------------------------------
Series([], Name: count, dtype: int64)
--------------------------------------------------
prices.isSale
False    1364
Name: count, dtype: int64
--------------------------------------------------
Series([], Name: count, dtype: int64)
--------------------------------------------------
Series([], Name: count, dtype: int64)
--------------------------------------------------
prices.shipping
Free Shipping on orders over $35    49
Name: count, dtype: int64
--------------------------------------------------

# HANDLING MISSING VALUES

In [20]:
df.dropna(subset = ['id'] , inplace = True)

In [24]:
df.isnull().sum()

id                         0
dateAdded                  0
dateUpdated                0
asins                   9995
brand                      0
categories                 0
primaryCategories          0
colors                     0
dimension               9535
ean / upc                  0
imageURLs               7357
keys                       0
manufacturer            8638
manufacturerNumber      8569
name                       0
prices.amountMax           0
prices.amountMin           0
prices.availability        0
prices.color               0
prices.condition       10000
prices.currency            0
prices.dateAdded       10000
prices.dateSeen            0
prices.isSale           8636
prices.merchant        10000
prices.offer               0
prices.returnPolicy    10000
prices.shipping         9951
prices.size                0
prices.sourceURLs          0
sizes                      0
sourceURLs                 0
dtype: int64

In [27]:
df['asins'].unique()

array([nan, 'B003DSG4EM,B003DSG4GK,B003DSG4FG',
       'B000OCQ19S,B000OCT69A,B000AOZK60,B00B1PI8JS,B000OCRIYU,B000AP3BEW,B000OCQ19I,B000AP0R44',
       'B01B6609BG', 'B00J2IK7Z4'], dtype=object)