In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Dataset exploration (1).zip to Dataset exploration (1).zip

In [ ]:
import pandas as pd
import zipfile
import os

# Unzip the uploaded file first
with zipfile.ZipFile('Dataset exploration (1).zip', 'r') as zip_ref:
    zip_ref.extractall('.')

# Correcting the path to one of the available CSV files
csv_file_path = 'Dataset exploration/day.csv'

# Check if the file exists at the assumed path
if not os.path.exists(csv_file_path):
    # If not, try to list the contents of the extracted directory to find the correct path
    print(f"File not found at {csv_file_path}. Listing contents of 'Dataset exploration' folder:")
    for root, dirs, files in os.walk('Dataset exploration'):
        for name in files:
            print(os.path.join(root, name))
    # If the file exists but has a different name or path, adjust csv_file_path accordingly

df = pd.read_csv(csv_file_path, encoding='unicode_escape')
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [ ]:
import pandas as pd
import os

# Define the path to the hour.csv file
hour_csv_file_path = 'Dataset exploration/hour.csv'

# Check if the file exists
if os.path.exists(hour_csv_file_path):
    df_hour = pd.read_csv(hour_csv_file_path, encoding='unicode_escape')
    print("Successfully loaded hour.csv:")
    display(df_hour.head())
else:
    print(f"Error: '{hour_csv_file_path}' not found. Please ensure the file is extracted.")

Successfully loaded hour.csv:

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [ ]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [ ]:
df_hour.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [ ]:
# convert date
df['dteday'] = pd.to_datetime(df['dteday'])
df_hour['dteday'] = pd.to_datetime(df_hour['dteday'])

for dframe in [df, df_hour]:
    dframe['day'] = dframe['dteday'].dt.day
    dframe['month'] = dframe['dteday'].dt.month
    dframe['year'] = dframe['dteday'].dt.year
    dframe['dayofweek'] = dframe['dteday'].dt.dayofweek
    dframe['is_weekend'] = dframe['dayofweek'].isin([5,6]).astype(int)

In [ ]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,...,hum,windspeed,casual,registered,cnt,day,month,year,dayofweek,is_weekend
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,...,0.805833,0.160446,331,654,985,1,1,2011,5,1
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,...,0.696087,0.248539,131,670,801,2,1,2011,6,1
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,...,0.437273,0.248309,120,1229,1349,3,1,2011,0,0
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,...,0.590435,0.160296,108,1454,1562,4,1,2011,1,0
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,...,0.436957,0.186900,82,1518,1600,5,1,2011,2,0

In [ ]:
import numpy as np

for df_current in [df, df_hour]:
    df_current['month_sin'] = np.sin(2 * np.pi * df_current['month']/12)
    df_current['month_cos'] = np.cos(2 * np.pi * df_current['month']/12)

In [ ]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,...,casual,registered,cnt,day,month,year,dayofweek,is_weekend,month_sin,month_cos
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,...,331,654,985,1,1,2011,5,1,0.5,0.866025
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,...,131,670,801,2,1,2011,6,1,0.5,0.866025
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,...,120,1229,1349,3,1,2011,0,0,0.5,0.866025
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,...,108,1454,1562,4,1,2011,1,0,0.5,0.866025
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,...,82,1518,1600,5,1,2011,2,0,0.5,0.866025

In [ ]:
df.head(15)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,...,casual,registered,cnt,day,month,year,dayofweek,is_weekend,month_sin,month_cos
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,...,331,654,985,1,1,2011,5,1,0.5,0.866025
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,...,131,670,801,2,1,2011,6,1,0.5,0.866025
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,...,120,1229,1349,3,1,2011,0,0,0.5,0.866025
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,...,108,1454,1562,4,1,2011,1,0,0.5,0.866025
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,...,82,1518,1600,5,1,2011,2,0,0.5,0.866025
5,6,2011-01-06,1,0,1,0,4,1,1,0.204348,...,88,1518,1606,6,1,2011,3,0,0.5,0.866025
6,7,2011-01-07,1,0,1,0,5,1,2,0.196522,...,148,1362,1510,7,1,2011,4,0,0.5,0.866025
7,8,2011-01-08,1,0,1,0,6,0,2,0.165000,...,68,891,959,8,1,2011,5,1,0.5,0.866025
8,9,2011-01-09,1,0,1,0,0,0,1,0.138333,...,54,768,822,9,1,2011,6,1,0.5,0.866025
9,10,2011-01-10,1,0,1,0,1,1,1,0.150833,...,41,1280,1321,10,1,2011,0,0,0.5,0.866025
10,11,2011-01-11,1,0,1,0,2,1,2,0.169091,...,43,1220,1263,11,1,2011,1,0,0.5,0.866025
11,12,2011-01-12,1,0,1,0,3,1,1,0.172727,...,25,1137,1162,12,1,2011,2,0,0.5,0.866025
12,13,2011-01-13,1,0,1,0,4,1,1,0.165000,...,38,1368,1406,13,1,2011,3,0,0.5,0.866025
13,14,2011-01-14,1,0,1,0,5,1,1,0.160870,...,54,1367,1421,14,1,2011,4,0,0.5,0.866025
14,15,2011-01-15,1,0,1,0,6,0,2,0.233333,...,222,1026,1248,15,1,2011,5,1,0.5,0.866025

In [ ]:
for df_current in [df, df_hour]:
    df_current['weather_severity'] = (
        df_current['weathersit'] *
        (1 + df_current['windspeed']) *
        (1 + df_current['hum'])
    )

In [ ]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,...,registered,cnt,day,month,year,dayofweek,is_weekend,month_sin,month_cos,weather_severity
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,...,654,985,1,1,2011,5,1,0.5,0.866025,4.191143
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,...,670,801,2,1,2011,6,1,0.5,0.866025,4.235262
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,...,1229,1349,3,1,2011,0,0,0.5,0.866025,1.794161
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,...,1454,1562,4,1,2011,1,0,0.5,0.866025,1.845375
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,...,1518,1600,5,1,2011,2,0,0.5,0.866025,1.705524

In [ ]:
for df_current in [df, df_hour]:
    df_current['comfort_index'] = (
        (1 - abs(df_current['temp'] - df_current['atemp'])) *
        (1 - df_current['hum']) *
        (1 - df_current['windspeed'])
    )

In [ ]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,...,cnt,day,month,year,dayofweek,is_weekend,month_sin,month_cos,weather_severity,comfort_index
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,...,985,1,1,2011,5,1,0.5,0.866025,4.191143,0.159842
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,...,801,2,1,2011,6,1,0.5,0.866025,4.235262,0.226155
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,...,1349,3,1,2011,0,0,0.5,0.866025,1.794161,0.420053
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,...,1562,4,1,2011,1,0,0.5,0.866025,1.845375,0.339744
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,...,1600,5,1,2011,2,0,0.5,0.866025,1.705524,0.456751

In [ ]:
for df_current in [df, df_hour]:
    df_current['is_peak_season'] = df_current['month'].isin([5, 6, 7, 8]).astype(int)

In [ ]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,...,day,month,year,dayofweek,is_weekend,month_sin,month_cos,weather_severity,comfort_index,is_peak_season
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,...,1,1,2011,5,1,0.5,0.866025,4.191143,0.159842,0
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,...,2,1,2011,6,1,0.5,0.866025,4.235262,0.226155,0
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,...,3,1,2011,0,0,0.5,0.866025,1.794161,0.420053,0
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,...,4,1,2011,1,0,0.5,0.866025,1.845375,0.339744,0
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,...,5,1,2011,2,0,0.5,0.866025,1.705524,0.456751,0

In [ ]:
for d in [df, df_hour]:
    print(d[d['is_peak_season'] == 1])

     instant     dteday  season  yr  mnth  holiday  weekday  workingday  \
120      121 2011-05-01       2   0     5        0        0           0
121      122 2011-05-02       2   0     5        0        1           1
122      123 2011-05-03       2   0     5        0        2           1
123      124 2011-05-04       2   0     5        0        3           1
124      125 2011-05-05       2   0     5        0        4           1
..       ...        ...     ...  ..   ...      ...      ...         ...
604      605 2012-08-27       3   1     8        0        1           1
605      606 2012-08-28       3   1     8        0        2           1
606      607 2012-08-29       3   1     8        0        3           1
607      608 2012-08-30       3   1     8        0        4           1
608      609 2012-08-31       3   1     8        0        5           1

     weathersit      temp  ...  day  month  year  dayofweek  is_weekend  \
120           2  0.451667  ...    1      5  2011          6           1
121           2  0.549167  ...    2      5  2011          0           0
122           2  0.616667  ...    3      5  2011          1           0
123           2  0.414167  ...    4      5  2011          2           0
124           1  0.459167  ...    5      5  2011          3           0
..          ...       ...  ...  ...    ...   ...        ...         ...
604           1  0.703333  ...   27      8  2012          0           0
605           1  0.728333  ...   28      8  2012          1           0
606           1  0.685000  ...   29      8  2012          2           0
607           1  0.706667  ...   30      8  2012          3           0
608           1  0.764167  ...   31      8  2012          4           0

     month_sin  month_cos  weather_severity  comfort_index  is_peak_season
120   0.500000  -0.866025          3.898975       0.211877               1
121   0.500000  -0.866025          4.094751       0.216866               1
122   0.500000  -0.866025          4.557235       0.192230               1
123   0.500000  -0.866025          4.617153       0.174739               1
124   0.500000  -0.866025          1.870762       0.384889               1
..         ...        ...               ...            ...             ...
604  -0.866025  -0.500000          1.953179       0.223453               1
605  -0.866025  -0.500000          1.929299       0.288300               1
606  -0.866025  -0.500000          1.726789       0.377915               1
607  -0.866025  -0.500000          1.713065       0.357628               1
608  -0.866025  -0.500000          1.855046       0.317337               1

[246 rows x 26 columns]
       instant     dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
2786      2787 2011-05-01       2   0     5   0        0        0           0
2787      2788 2011-05-01       2   0     5   1        0        0           0
2788      2789 2011-05-01       2   0     5   2        0        0           0
2789      2790 2011-05-01       2   0     5   3        0        0           0
2790      2791 2011-05-01       2   0     5   4        0        0           0
...        ...        ...     ...  ..   ...  ..      ...      ...         ...
14486    14487 2012-08-31       3   1     8  19        0        5           1
14487    14488 2012-08-31       3   1     8  20        0        5           1
14488    14489 2012-08-31       3   1     8  21        0        5           1
14489    14490 2012-08-31       3   1     8  22        0        5           1
14490    14491 2012-08-31       3   1     8  23        0        5           1

       weathersit  ...  day  month  year  dayofweek  is_weekend  month_sin  \
2786            1  ...    1      5  2011          6           1   0.500000
2787            1  ...    1      5  2011          6           1   0.500000
2788            1  ...    1      5  2011          6           1   0.500000
2789            1  ...    1      5  2011          6           1   0.500000
2790            1  ...    1      5  2011          6           1   0.500000
...           ...  ...  ...    ...   ...        ...         ...        ...
14486           1  ...   31      8  2012          4           0  -0.866025
14487           1  ...   31      8  2012          4           0  -0.866025
14488           1  ...   31      8  2012          4           0  -0.866025
14489           1  ...   31      8  2012          4           0  -0.866025
14490           1  ...   31      8  2012          4           0  -0.866025

       month_cos  weather_severity  comfort_index  is_peak_season
2786   -0.866025          1.819632       0.299170               1
2787   -0.866025          1.866605       0.276439               1
2788   -0.866025          1.954965       0.205100               1
2789   -0.866025          2.010190       0.159723               1
2790   -0.866025          1.943920       0.212964               1
...          ...               ...            ...             ...
14486  -0.500000          1.690107       0.416076               1
14487  -0.500000          1.690107       0.416076               1
14488  -0.500000          1.886520       0.322305               1
14489  -0.500000          1.886520       0.322305               1
14490  -0.500000          1.789290       0.320485               1

[5891 rows x 27 columns]

In [ ]:
# Define rush hours (e.g., 7-9 AM and 5-7 PM)
df_hour['is_rush_hour'] = ((df_hour['hr'] >= 7) & (df_hour['hr'] <= 9)) | ((df_hour['hr'] >= 17) & (df_hour['hr'] <= 19)).astype(int)

In [ ]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,...,day,month,year,dayofweek,is_weekend,month_sin,month_cos,weather_severity,comfort_index,is_peak_season
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,...,1,1,2011,5,1,0.5,0.866025,4.191143,0.159842,0
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,...,2,1,2011,6,1,0.5,0.866025,4.235262,0.226155,0
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,...,3,1,2011,0,0,0.5,0.866025,1.794161,0.420053,0
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,...,4,1,2011,1,0,0.5,0.866025,1.845375,0.339744,0
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,...,5,1,2011,2,0,0.5,0.866025,1.705524,0.456751,0

In [ ]:
# show the whole "is_rush_hour" column
print(df_hour['is_rush_hour'])

# or, to see just the first few values
print(df_hour['is_rush_hour'].head())

0        False
1        False
2        False
3        False
4        False
         ...
17374     True
17375    False
17376    False
17377    False
17378    False
Name: is_rush_hour, Length: 17379, dtype: bool
0    False
1    False
2    False
3    False
4    False
Name: is_rush_hour, dtype: bool

In [ ]:
# show the whole column
print(df_hour['workday_intensity'])

# or just the first few values
print(df_hour['workday_intensity'].head())

0        0
1        0
2        0
3        0
4        0
        ..
17374    1
17375    0
17376    0
17377    0
17378    0
Name: workday_intensity, Length: 17379, dtype: int64
0    0
1    0
2    0
3    0
4    0
Name: workday_intensity, dtype: int64

In [ ]:
for df_current in [df, df_hour]:
    df_current['registered_minus_casual'] = df_current['registered'] - df_current['casual']

In [ ]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,...,month,year,dayofweek,is_weekend,month_sin,month_cos,weather_severity,comfort_index,is_peak_season,registered_minus_casual
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,...,1,2011,5,1,0.5,0.866025,4.191143,0.159842,0,323
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,...,1,2011,6,1,0.5,0.866025,4.235262,0.226155,0,539
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,...,1,2011,0,0,0.5,0.866025,1.794161,0.420053,0,1109
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,...,1,2011,1,0,0.5,0.866025,1.845375,0.339744,0,1346
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,...,1,2011,2,0,0.5,0.866025,1.705524,0.456751,0,1436